// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package msg.grpc;

public interface BlockOrBuilder extends
    // @@protoc_insertion_point(interface_extends:msg.Block)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.msg.Block.Type type = 1;</code>
   */
  int getTypeValue();
  /**
   * <code>.msg.Block.Type type = 1;</code>
   */
  msg.grpc.Block.Type getType();

  /**
   * <pre>
   * if type is cube, then w means width, h means height.
   * if type is cylinder, the w means radius, h means height.
   * </pre>
   *
   * <code>double w = 2;</code>
   */
  double getW();

  /**
   * <code>double h = 3;</code>
   */
  double getH();
}
