// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package msg.grpc;

public interface ControlCmdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:msg.ControlCmd)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.msg.ControlCmd.CtrlCmd cmd = 1;</code>
   */
  int getCmdValue();
  /**
   * <code>.msg.ControlCmd.CtrlCmd cmd = 1;</code>
   */
  msg.grpc.ControlCmd.CtrlCmd getCmd();
}
