// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package msg.grpc;

public interface DriveOrBuilder extends
    // @@protoc_insertion_point(interface_extends:msg.Drive)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.msg.Drive.DriveCmd drivecmd = 1;</code>
   */
  int getDrivecmdValue();
  /**
   * <code>.msg.Drive.DriveCmd drivecmd = 1;</code>
   */
  msg.grpc.Drive.DriveCmd getDrivecmd();
}
