// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package msg.grpc;

public interface LogStrOrBuilder extends
    // @@protoc_insertion_point(interface_extends:msg.LogStr)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string log = 1;</code>
   */
  java.lang.String getLog();
  /**
   * <code>string log = 1;</code>
   */
  com.google.protobuf.ByteString
      getLogBytes();
}
