// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package msg.grpc;

/**
 * Protobuf type {@code msg.Map}
 */
public  final class Map extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:msg.Map)
    MapOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Map.newBuilder() to construct.
  private Map(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Map() {
    roomwidth_ = 0D;
    roomheight_ = 0D;
    blocks_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Map(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            roomwidth_ = input.readDouble();
            break;
          }
          case 17: {

            roomheight_ = input.readDouble();
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              blocks_ = new java.util.ArrayList<msg.grpc.Block>();
              mutable_bitField0_ |= 0x00000004;
            }
            blocks_.add(
                input.readMessage(msg.grpc.Block.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        blocks_ = java.util.Collections.unmodifiableList(blocks_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return msg.grpc.Msg.internal_static_msg_Map_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return msg.grpc.Msg.internal_static_msg_Map_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            msg.grpc.Map.class, msg.grpc.Map.Builder.class);
  }

  private int bitField0_;
  public static final int ROOMWIDTH_FIELD_NUMBER = 1;
  private double roomwidth_;
  /**
   * <code>double roomwidth = 1;</code>
   */
  public double getRoomwidth() {
    return roomwidth_;
  }

  public static final int ROOMHEIGHT_FIELD_NUMBER = 2;
  private double roomheight_;
  /**
   * <code>double roomheight = 2;</code>
   */
  public double getRoomheight() {
    return roomheight_;
  }

  public static final int BLOCKS_FIELD_NUMBER = 3;
  private java.util.List<msg.grpc.Block> blocks_;
  /**
   * <code>repeated .msg.Block blocks = 3;</code>
   */
  public java.util.List<msg.grpc.Block> getBlocksList() {
    return blocks_;
  }
  /**
   * <code>repeated .msg.Block blocks = 3;</code>
   */
  public java.util.List<? extends msg.grpc.BlockOrBuilder> 
      getBlocksOrBuilderList() {
    return blocks_;
  }
  /**
   * <code>repeated .msg.Block blocks = 3;</code>
   */
  public int getBlocksCount() {
    return blocks_.size();
  }
  /**
   * <code>repeated .msg.Block blocks = 3;</code>
   */
  public msg.grpc.Block getBlocks(int index) {
    return blocks_.get(index);
  }
  /**
   * <code>repeated .msg.Block blocks = 3;</code>
   */
  public msg.grpc.BlockOrBuilder getBlocksOrBuilder(
      int index) {
    return blocks_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (roomwidth_ != 0D) {
      output.writeDouble(1, roomwidth_);
    }
    if (roomheight_ != 0D) {
      output.writeDouble(2, roomheight_);
    }
    for (int i = 0; i < blocks_.size(); i++) {
      output.writeMessage(3, blocks_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (roomwidth_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, roomwidth_);
    }
    if (roomheight_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, roomheight_);
    }
    for (int i = 0; i < blocks_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, blocks_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof msg.grpc.Map)) {
      return super.equals(obj);
    }
    msg.grpc.Map other = (msg.grpc.Map) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getRoomwidth())
        == java.lang.Double.doubleToLongBits(
            other.getRoomwidth()));
    result = result && (
        java.lang.Double.doubleToLongBits(getRoomheight())
        == java.lang.Double.doubleToLongBits(
            other.getRoomheight()));
    result = result && getBlocksList()
        .equals(other.getBlocksList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ROOMWIDTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getRoomwidth()));
    hash = (37 * hash) + ROOMHEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getRoomheight()));
    if (getBlocksCount() > 0) {
      hash = (37 * hash) + BLOCKS_FIELD_NUMBER;
      hash = (53 * hash) + getBlocksList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static msg.grpc.Map parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static msg.grpc.Map parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static msg.grpc.Map parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static msg.grpc.Map parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static msg.grpc.Map parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static msg.grpc.Map parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static msg.grpc.Map parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static msg.grpc.Map parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static msg.grpc.Map parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static msg.grpc.Map parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static msg.grpc.Map parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static msg.grpc.Map parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(msg.grpc.Map prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code msg.Map}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:msg.Map)
      msg.grpc.MapOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return msg.grpc.Msg.internal_static_msg_Map_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return msg.grpc.Msg.internal_static_msg_Map_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              msg.grpc.Map.class, msg.grpc.Map.Builder.class);
    }

    // Construct using msg.grpc.Map.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBlocksFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      roomwidth_ = 0D;

      roomheight_ = 0D;

      if (blocksBuilder_ == null) {
        blocks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        blocksBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return msg.grpc.Msg.internal_static_msg_Map_descriptor;
    }

    @java.lang.Override
    public msg.grpc.Map getDefaultInstanceForType() {
      return msg.grpc.Map.getDefaultInstance();
    }

    @java.lang.Override
    public msg.grpc.Map build() {
      msg.grpc.Map result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public msg.grpc.Map buildPartial() {
      msg.grpc.Map result = new msg.grpc.Map(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.roomwidth_ = roomwidth_;
      result.roomheight_ = roomheight_;
      if (blocksBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          blocks_ = java.util.Collections.unmodifiableList(blocks_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.blocks_ = blocks_;
      } else {
        result.blocks_ = blocksBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof msg.grpc.Map) {
        return mergeFrom((msg.grpc.Map)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(msg.grpc.Map other) {
      if (other == msg.grpc.Map.getDefaultInstance()) return this;
      if (other.getRoomwidth() != 0D) {
        setRoomwidth(other.getRoomwidth());
      }
      if (other.getRoomheight() != 0D) {
        setRoomheight(other.getRoomheight());
      }
      if (blocksBuilder_ == null) {
        if (!other.blocks_.isEmpty()) {
          if (blocks_.isEmpty()) {
            blocks_ = other.blocks_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureBlocksIsMutable();
            blocks_.addAll(other.blocks_);
          }
          onChanged();
        }
      } else {
        if (!other.blocks_.isEmpty()) {
          if (blocksBuilder_.isEmpty()) {
            blocksBuilder_.dispose();
            blocksBuilder_ = null;
            blocks_ = other.blocks_;
            bitField0_ = (bitField0_ & ~0x00000004);
            blocksBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBlocksFieldBuilder() : null;
          } else {
            blocksBuilder_.addAllMessages(other.blocks_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      msg.grpc.Map parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (msg.grpc.Map) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private double roomwidth_ ;
    /**
     * <code>double roomwidth = 1;</code>
     */
    public double getRoomwidth() {
      return roomwidth_;
    }
    /**
     * <code>double roomwidth = 1;</code>
     */
    public Builder setRoomwidth(double value) {
      
      roomwidth_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double roomwidth = 1;</code>
     */
    public Builder clearRoomwidth() {
      
      roomwidth_ = 0D;
      onChanged();
      return this;
    }

    private double roomheight_ ;
    /**
     * <code>double roomheight = 2;</code>
     */
    public double getRoomheight() {
      return roomheight_;
    }
    /**
     * <code>double roomheight = 2;</code>
     */
    public Builder setRoomheight(double value) {
      
      roomheight_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double roomheight = 2;</code>
     */
    public Builder clearRoomheight() {
      
      roomheight_ = 0D;
      onChanged();
      return this;
    }

    private java.util.List<msg.grpc.Block> blocks_ =
      java.util.Collections.emptyList();
    private void ensureBlocksIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        blocks_ = new java.util.ArrayList<msg.grpc.Block>(blocks_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        msg.grpc.Block, msg.grpc.Block.Builder, msg.grpc.BlockOrBuilder> blocksBuilder_;

    /**
     * <code>repeated .msg.Block blocks = 3;</code>
     */
    public java.util.List<msg.grpc.Block> getBlocksList() {
      if (blocksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(blocks_);
      } else {
        return blocksBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .msg.Block blocks = 3;</code>
     */
    public int getBlocksCount() {
      if (blocksBuilder_ == null) {
        return blocks_.size();
      } else {
        return blocksBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .msg.Block blocks = 3;</code>
     */
    public msg.grpc.Block getBlocks(int index) {
      if (blocksBuilder_ == null) {
        return blocks_.get(index);
      } else {
        return blocksBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .msg.Block blocks = 3;</code>
     */
    public Builder setBlocks(
        int index, msg.grpc.Block value) {
      if (blocksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBlocksIsMutable();
        blocks_.set(index, value);
        onChanged();
      } else {
        blocksBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .msg.Block blocks = 3;</code>
     */
    public Builder setBlocks(
        int index, msg.grpc.Block.Builder builderForValue) {
      if (blocksBuilder_ == null) {
        ensureBlocksIsMutable();
        blocks_.set(index, builderForValue.build());
        onChanged();
      } else {
        blocksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .msg.Block blocks = 3;</code>
     */
    public Builder addBlocks(msg.grpc.Block value) {
      if (blocksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBlocksIsMutable();
        blocks_.add(value);
        onChanged();
      } else {
        blocksBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .msg.Block blocks = 3;</code>
     */
    public Builder addBlocks(
        int index, msg.grpc.Block value) {
      if (blocksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBlocksIsMutable();
        blocks_.add(index, value);
        onChanged();
      } else {
        blocksBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .msg.Block blocks = 3;</code>
     */
    public Builder addBlocks(
        msg.grpc.Block.Builder builderForValue) {
      if (blocksBuilder_ == null) {
        ensureBlocksIsMutable();
        blocks_.add(builderForValue.build());
        onChanged();
      } else {
        blocksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .msg.Block blocks = 3;</code>
     */
    public Builder addBlocks(
        int index, msg.grpc.Block.Builder builderForValue) {
      if (blocksBuilder_ == null) {
        ensureBlocksIsMutable();
        blocks_.add(index, builderForValue.build());
        onChanged();
      } else {
        blocksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .msg.Block blocks = 3;</code>
     */
    public Builder addAllBlocks(
        java.lang.Iterable<? extends msg.grpc.Block> values) {
      if (blocksBuilder_ == null) {
        ensureBlocksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, blocks_);
        onChanged();
      } else {
        blocksBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .msg.Block blocks = 3;</code>
     */
    public Builder clearBlocks() {
      if (blocksBuilder_ == null) {
        blocks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        blocksBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .msg.Block blocks = 3;</code>
     */
    public Builder removeBlocks(int index) {
      if (blocksBuilder_ == null) {
        ensureBlocksIsMutable();
        blocks_.remove(index);
        onChanged();
      } else {
        blocksBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .msg.Block blocks = 3;</code>
     */
    public msg.grpc.Block.Builder getBlocksBuilder(
        int index) {
      return getBlocksFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .msg.Block blocks = 3;</code>
     */
    public msg.grpc.BlockOrBuilder getBlocksOrBuilder(
        int index) {
      if (blocksBuilder_ == null) {
        return blocks_.get(index);  } else {
        return blocksBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .msg.Block blocks = 3;</code>
     */
    public java.util.List<? extends msg.grpc.BlockOrBuilder> 
         getBlocksOrBuilderList() {
      if (blocksBuilder_ != null) {
        return blocksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(blocks_);
      }
    }
    /**
     * <code>repeated .msg.Block blocks = 3;</code>
     */
    public msg.grpc.Block.Builder addBlocksBuilder() {
      return getBlocksFieldBuilder().addBuilder(
          msg.grpc.Block.getDefaultInstance());
    }
    /**
     * <code>repeated .msg.Block blocks = 3;</code>
     */
    public msg.grpc.Block.Builder addBlocksBuilder(
        int index) {
      return getBlocksFieldBuilder().addBuilder(
          index, msg.grpc.Block.getDefaultInstance());
    }
    /**
     * <code>repeated .msg.Block blocks = 3;</code>
     */
    public java.util.List<msg.grpc.Block.Builder> 
         getBlocksBuilderList() {
      return getBlocksFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        msg.grpc.Block, msg.grpc.Block.Builder, msg.grpc.BlockOrBuilder> 
        getBlocksFieldBuilder() {
      if (blocksBuilder_ == null) {
        blocksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            msg.grpc.Block, msg.grpc.Block.Builder, msg.grpc.BlockOrBuilder>(
                blocks_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        blocks_ = null;
      }
      return blocksBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:msg.Map)
  }

  // @@protoc_insertion_point(class_scope:msg.Map)
  private static final msg.grpc.Map DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new msg.grpc.Map();
  }

  public static msg.grpc.Map getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Map>
      PARSER = new com.google.protobuf.AbstractParser<Map>() {
    @java.lang.Override
    public Map parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Map(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Map> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Map> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public msg.grpc.Map getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

