// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package msg.grpc;

public interface PointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:msg.Point)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double posx = 1;</code>
   */
  double getPosx();

  /**
   * <code>double posy = 2;</code>
   */
  double getPosy();
}
