// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package msg.grpc;

public interface RBPathOrBuilder extends
    // @@protoc_insertion_point(interface_extends:msg.RBPath)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .msg.Point pos = 1;</code>
   */
  java.util.List<msg.grpc.Point> 
      getPosList();
  /**
   * <code>repeated .msg.Point pos = 1;</code>
   */
  msg.grpc.Point getPos(int index);
  /**
   * <code>repeated .msg.Point pos = 1;</code>
   */
  int getPosCount();
  /**
   * <code>repeated .msg.Point pos = 1;</code>
   */
  java.util.List<? extends msg.grpc.PointOrBuilder> 
      getPosOrBuilderList();
  /**
   * <code>repeated .msg.Point pos = 1;</code>
   */
  msg.grpc.PointOrBuilder getPosOrBuilder(
      int index);

  /**
   * <code>double starttime = 2;</code>
   */
  double getStarttime();

  /**
   * <code>double endtime = 3;</code>
   */
  double getEndtime();
}
