// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package msg.grpc;

public interface RBPositionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:msg.RBPosition)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.msg.Point pos = 1;</code>
   */
  boolean hasPos();
  /**
   * <code>.msg.Point pos = 1;</code>
   */
  msg.grpc.Point getPos();
  /**
   * <code>.msg.Point pos = 1;</code>
   */
  msg.grpc.PointOrBuilder getPosOrBuilder();

  /**
   * <code>double angle = 2;</code>
   */
  double getAngle();

  /**
   * <code>double vx = 3;</code>
   */
  double getVx();

  /**
   * <code>double vy = 4;</code>
   */
  double getVy();

  /**
   * <code>double timestamp = 5;</code>
   */
  double getTimestamp();
}
