// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package msg.grpc;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:msg.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.msg.Response.Status status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>.msg.Response.Status status = 1;</code>
   */
  msg.grpc.Response.Status getStatus();
}
