// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package msg.grpc;

public interface VoiceStrOrBuilder extends
    // @@protoc_insertion_point(interface_extends:msg.VoiceStr)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string voice = 1;</code>
   */
  java.lang.String getVoice();
  /**
   * <code>string voice = 1;</code>
   */
  com.google.protobuf.ByteString
      getVoiceBytes();

  /**
   * <code>int32 timestamp = 2;</code>
   */
  int getTimestamp();
}
